### ISSUE TITLE
Cant reform caravan from Crashed ship

### ISSUE THREAD

**Issue by deamon20061** [Taranchuk/Recon-and-Discovery#1]
there we have an event as Crashed ship. It is work but after you have done and there is no enemies you need to wait for 3!!! days without a battle for regrouping caravan.

Because on world map only 2 option - zoom on the territory or create a village.

So other events working well but this on with such a problem.  (i can't make a village sometime since its too close to another faction

**Comment by Taranchuk** [comment]
You can simply select all the pawns and order them to go to the edge of the map and you are on the world map. This is a vanilla feature.

**Comment by Taranchuk** [comment]
I can’t make it possible to simultaneously reform the caravan and exit through the map. Something one of them should stay.

**Comment by deamon20061** [comment]
No, i can't because in this case all animals will be lost - i need them to collect treasure from this place

Also another bug - i cant establish Geothermal source from mod - just game don't let do this in any available place.

**Comment by deamon20061** [comment]
> I can’t make it possible to simultaneously reform the caravan and exit through the map. Something one of them should stay.

that's what i was thinking also but why other events working OK but this one so terrible...

**Comment by Taranchuk** [comment]
Added the ability to reform caravans in all maps
